### PR TITLE
Relax childprocess dependency version

### PR DESCRIPTION
**Pull request by delphaber**
`childprocess` turned `1` on January, so I tried to relax `childprocess` dependency version from `~> 0.6` to `>= 0.6.3`.

Let's see if CI passes :)

### CODE REVIEW

**Comment by delphaber** [comment]
Dang! It breaks on Windows! Maybe because of https://github.com/enkessler/childprocess/pull/132 ? 🤔

**Comment by sds** [comment]
Thanks for the PR, @delphaber. 

Yes, `childprocess` requires the `ffi` gem to be installed on Windows machines. However, it doesn't require this by default since most use cases don't need it and it slows down installs. See https://github.com/enkessler/childprocess/issues/150 for context. 

I think the simplest workaround is to add the following to this project's `Gemfile` so we get the tests to pass on Windows:

```ruby
gem 'ffi' if Gem.win_platform?
```

What do you think?

**Comment by delphaber** [comment]
Makes totally sense! thanks :) I'm updating the PR

**Comment by delphaber** [comment]
Done! Let's wait for the CIs :)

**Comment by sds** [comment]
Thanks for the PR! Fixed the broken test and merged in #653.

**Pull request closed without merging**
